### ISSUE TITLE
Use JSON-endpoint instead of parsing HTML

### ISSUE THREAD

**Issue by gernberg** [adsa95/driveback#1]
Kul lib :-)

I would consider changing the script so that it uses the JSON-endpoint: https://www.driveback.se/resor.json

Instead of relying on the HTML-present on the website since it may change at any time without prior notice (hint hint 😉).

**Comment by adsa95** [comment]
Awesome, thanks!

**Comment by gernberg** [comment]
Hojta till om du behöver ngt mer i jsonformat så kan vi säkert styra upp det. :)

**Comment by adsa95** [comment]
Om ni planerar att ändra bokningslänkarna vore det toppen att få med dem i JSON men annars verkade det mesta finnas där! :)
